# Generated by Django 5.0.7 on 2025-08-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_priorit_a3d3b1_idx',
            old_name='projects_pr_priority_3a0cc5_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_deadlin_bd2912_idx',
            old_name='projects_pr_deadlin_8a53cc_idx',
        ),
    ]
